# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)

In [14]:
torch.__version__

'2.1.0+cu118'

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
small_tensor = torch.rand(1, 7)

# Perform matrix multiplication
tensor.mm(small_tensor.T)

tensor([[0.6859],
        [0.8579],
        [0.9151],
        [1.3375],
        [1.2328],
        [1.3734],
        [1.6196]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7, 7)
small_tensor = torch.rand(1, 7)

# Matrix multiply tensors
tensor.mm(small_tensor.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [75]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [79]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
torch.cuda.device_count()

if torch.cuda.is_available():
  device = 'cuda'
else:
  device = 'cpu'
# Create two random tensors on GPU
tensor1 = torch.rand(2, 3, device=device)
torch.manual_seed(1234)
tensor2 = torch.rand(2, 3, device=device)

In [80]:
tensor1

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [81]:
tensor2

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [82]:
# Perform matmul on tensor_A and tensor_B
tensor_mm = tensor1.mm(tensor2.T)

In [83]:
tensor_mm

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [47]:
tensor_mm[0]

tensor([1.1000, 0.7324], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [43]:
# Find max
print (f"Tensor mm max: {tensor_mm.max()}")
# Find min
print (f"Tesnor mm min: {tensor_mm.min()}")

Tensor mm max: 1.2478716373443604
Tesnor mm min: 0.46387672424316406


### 9. Find the maximum and minimum index values of the output of 7.

In [72]:
print (f"Original tensor: \n {tensor_mm} \n")

'''
Tesnor dimensions
when index within a matrices we can get all the columns by tensor[:, i], where
i is the column number to view. We are basically setting the 0dim in the index
to return everything

to get all the rows we would do tensor[i, :] which would give you all the values
in each row

Dim 0 = step through each 'column'
Dim 1 = step through each 'row'
'''

# Find arg max
'''
Arg max will return the max indexc based on the dimension specifed
'''
print (f"Dim 0 argmax: {tensor_mm.argmax(dim=0)}")
print (f"Dim 1 argmax: {tensor_mm.argmax(dim=1)}")
print (f"Flat argmax: {tensor_mm.argmax()}")

# Find arg min
print (f"Dim 0 argmin: {tensor_mm.argmin(dim=0)}")
print (f"Dim 1 argmin: {tensor_mm.argmin(dim=1)}")
print (f"Flat argmin: {tensor_mm.argmin()}")

Original tensor: 
 tensor([[1.1000, 0.7324],
        [1.2479, 0.4639]], device='cuda:0') 

Dim 0 argmax: tensor([1, 0], device='cuda:0')
Dim 1 argmax: tensor([0, 0], device='cuda:0')
Flat argmax: 2
Dim 0 argmin: tensor([0, 1], device='cuda:0')
Dim 1 argmin: tensor([1, 1], device='cuda:0')
Flat argmin: 3


In [73]:
tensor_mm[0, :]

tensor([1.1000, 0.7324], device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [74]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
sq_rand_tensor = rand_tensor.squeeze()

# Print out tensors and their shapes
print (f"First tensor: \n")
print (f"{rand_tensor}")
print (f"Tensor shape: {rand_tensor.shape}\n")

print (f"Squeezed tensor: \n")
print (f"{sq_rand_tensor}")
print (f"Squeezed Tensor shape: {sq_rand_tensor.shape}\n")

First tensor: 

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor shape: torch.Size([1, 1, 1, 10])

Squeezed tensor: 

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed Tensor shape: torch.Size([10])

